foodweb/foodapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'food'
urlpatterns = [

    # path('', views.search_restaurant, name='search'),

    path('', views.show_restaurant, name='show_res'),

    path('<int:restaurant_id>/', views.detail_restaurant, name='detail_res'),

    path('<int:restaurant_id>/review', views.reviwe_restaurant, name='review_res'),

    path('<int:restaurant_id>/random_menu', views.random_menu_restaurant, name='random_res'),

    # path('', views.search_restaurant, name=''),

]

foodweb/foodweb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('foodapp.urls')),

]

foodweb/foodapp/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    number = models.CharField(max_length=20)
    time = models.CharField(max_length=200)
    location = models.TextField(max_length=200)


    def __str__(self):
        return self.name

class Menu(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Reviews(models.Model):
    reviews = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    reviews_text = models.CharField(max_length=500)
    point = models.IntegerField(default=0)
    review_date = models.DateTimeField('date published')

foodweb/foodapp/views.py
from django.shortcuts import render,get_object_or_404
from .models import Restaurant,Menu,Reviews
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
import random
# Create your views here.


def search_restaurant(request):
    return render(request,'foodapp/search_restaurant.html')

def show_restaurant(request):
    try:
        if request.GET['text_input']=="":
        # return render(request, 'foodapp/search_restaurant.html')
            try:
                r_list = Restaurant.objects.filter(type=request.GET['t_food'])
                context = {'list_name_r': r_list}
                return render(request, 'foodapp/search_restaurant.html', context)
            except(KeyError):
                context = {'error':'ใส่ข้อมูลร้าน'}
                return render(request, 'foodapp/search_restaurant.html',context)
        else:
            try:
                r_list = Restaurant.objects.filter(name__startswith=request.GET['text_input'],type=request.GET['t_food'])
                context = {'list_name_r': r_list}
                return render(request, 'foodapp/search_restaurant.html', context)
            except (KeyError,UnboundLocalError):
                r_list = Restaurant.objects.filter(name__startswith=request.GET['text_input'])
                if len(r_list)==0:
                    context = {'error': "ไม่พบรายชื่อร้านที่ค้นหา"}
                    return render(request, 'foodapp/search_restaurant.html', context)
                else:
                    context = {'list_name_r': r_list}
                    return render(request, 'foodapp/search_restaurant.html', context)
    except (KeyError):
        return render(request, 'foodapp/search_restaurant.html')

def detail_restaurant(request,restaurant_id):
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    context = {'restaurant': restaurant,'restaurant_reviews':restaurant.reviews_set.all().order_by('-review_date')}
    return render(request, 'foodapp/detail_restaurant.html', context)

def reviwe_restaurant(request,restaurant_id):
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    if request.POST["review"]=="":
        context = {'restaurant': restaurant,'error':'ใส่ข้อความรีวิว','restaurant_reviews':restaurant.reviews_set.all().order_by('-review_date')}
        return render(request, 'foodapp/detail_restaurant.html', context)
    else:
        try:
            restaurant.reviews_set.create(reviews_text=request.POST["review"], point=int(request.POST["point"]),review_date=timezone.now())
            return HttpResponseRedirect(reverse('food:detail_res', args=str(restaurant.id)))
        except (KeyError):
            context = {'restaurant': restaurant, 'error': 'ใส่คะแนนรีวิว','restaurant_reviews':restaurant.reviews_set.all().order_by('-review_date')}
            return render(request, 'foodapp/detail_restaurant.html', context)

def random_menu_restaurant(request,restaurant_id):
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    try:
        menu = restaurant.menu_set.all()
        menu_random = random.choice(menu)
        context = {'restaurant': restaurant,
                   'restaurant_reviews': restaurant.reviews_set.all().order_by('-review_date'),
                   'menu_random': menu_random}

    except (IndexError):
        return HttpResponseRedirect(reverse('food:detail_res', args=str(restaurant.id)))
    else:
        return render(request, 'foodapp/detail_restaurant.html', context)

foodweb/foodapp/templates/foodapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ restaurant.name }}</h1>
<ul>
{% for manu in restaurant.manu_set.all %}
    <li>{{ manu.name }}</li>
{% endfor %}

</ul>
<hr>
<h2>รีวิวร้าน</h2>
<ul>
{% for reviews in restaurant.reviews_set.all %}
    <li>{{ reviews.reviews_text }}  ----  {{ reviews.point }} คะแนน</li>
{% endfor %}
</ul>
</body>
</html>

foodweb/foodapp/templates/foodapp/detail_restaurant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <a href="{% url 'food:show_res' %}">กลับ</a>
</head>
<body>
<h1>{{ restaurant.name }}</h1>
<h4>สถานที่ : {{restaurant.location}}</h4>
<h4>เวลาเปิด-ปิด : {{restaurant.time}}</h4>
<h4>เบอร์โทร : {{restaurant.number}}</h4>
<form action="{% url 'food:random_res' restaurant.id  %}" method="post">
    {% csrf_token %}
    <input type="submit" value="สุ่มเมนูอาหาร">
    <input type="text" name="txt_random" value="{{menu_random}}" size="30" maxlength="30" disabled="disabled" />
</form>
<ul>
{% for menu in restaurant.menu_set.all %}
    <li>{{ menu.name }}</li>
{% endfor %}

</ul>
<hr>
<h2>รีวิวร้าน</h2>
<form action="{% url 'food:review_res' restaurant.id  %}" method="post">
    {% csrf_token %}
    <h5>คะแนน :
    <input type="radio" name="point" value="1" /> 1
    <input type="radio" name="point" value="2" /> 2
    <input type="radio" name="point" value="3" /> 3
    <input type="radio" name="point" value="4" /> 4
    <input type="radio" name="point" value="5" /> 5
    </h5>
    <textarea name= "review" cols= "45" rows= "5"></textarea> <br>
    <input type="submit" value="ยืนยัน">{{error}}
</form>
<ul>
{% for reviews in restaurant_reviews %}
    <li>{{ reviews.reviews_text }}</li>
    <li>{{ reviews.point }} คะแนน</li>
    <li>{{ reviews.review_date }}</li>
    <hr>
{% endfor %}
</ul>
</body>
</html>

foodweb/foodapp/templates/foodapp/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
{% for menu in restaurant.menu_set.all %}
    <li>{{ menu.name }}</li>
{% endfor %}

</ul>
</body>
</html>

foodweb/foodapp/templates/foodapp/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Foodapp</title>
</head>
<body>
<form action="{% url 'food:show' %}" method="post">
    {% csrf_token %}
    <input type="text" name="text_input" value=""/><br>
    <input type="radio" name="t_food" value="food" /> อาหาร
    <input type="radio" name="t_food" value="drink" /> เครื่องดื่ม  <br>
    <input type="submit" value="ค้นหา"> <br>
    {% if list_name_r %}
    <ul>
    {% for restaurant in list_name_r %}
    <li><a href="{% url 'food:detail' restaurant.id %}">{{ restaurant.name }}</a></li>
    {% endfor %}
    </ul>
    {% endif %}
</form>
</body>
</html>

foodweb/foodapp/templates/foodapp/search_restaurant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Foodapp</title>
</head>
<body>
<h1>ร้านอาหารหลังมอ</h1>
<form action="{% url 'food:show_res' %}" method="get">
    {% csrf_token %}
    <input type="text" name="text_input"/><br>
    <input type="radio" name="t_food" value="food" /> อาหาร
    <input type="radio" name="t_food" value="drink" /> เครื่องดื่ม  <br>
    <input type="submit" value="ค้นหา">{{error}} <br>
    {% if list_name_r %}
    <ul>
    {% for restaurant in list_name_r %}
    <li><a href="{% url 'food:detail_res' restaurant.id %}">{{ restaurant.name }}</a></li>
    {% endfor %}
    </ul>
    {% endif %}

</form>
</body>
</html>